version: "3"

services:

## Router
router01:
  image: mongo:4.0
  container_name: rydell-router-01
  command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
  ports:
    - 27117:27017
  volumes:
    - ./scripts:/scripts
router02:
  image: mongo:4.0
  container_name: rydell-router-02
  command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
  volumes:
    - ./scripts:/scripts
  ports:
    - 27118:27017
  links:
    - router01
    
  mongo1:
    hostname: mongo1
    image: mongo:latest
    expose:
      - 27017
    ports:
      - 30000:27017
    restart: always
    volumes:
      - /data1:/data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo2:
    hostname: mongo2
    image: mongo:latest
    expose:
      - 27017
    ports:
      - 30001:27017
    volumes:
      - /data2:/data/db
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo3:
    hostname: mongo3
    image: mongo:latest
    expose:
      - 27017
    ports:
      - 30002:27017
    volumes:
      - /data3:/data/db
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

volumes:
    data1:
    data2:
    data3: