version: "3"

services:

## Router
router01:
  image: mongo:4.0
  container_name: rydell-router-01
  command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
  ports:
    - 27117:27017
  volumes:
    - ./scripts:/scripts

## Config Servers
configsvr01:
  image: mongo:4.0
  container_name: rydell-mongo-config-01
  command: mongod --port 27017 --configsvr --replSet rs-config-server
  volumes:
    - ./scripts:/scripts
  ports:
    - 27119:27017
  links:
    - shard01-a
    - shard02-a
    - shard03-a
configsvr02:
  image: mongo:4.0
  container_name: rydell-mongo-config-02
  command: mongod --port 27017 --configsvr --replSet rs-config-server
  volumes:
    - ./scripts:/scripts
  ports:
    - 27120:27017
  links:
    - configsvr01
configsvr03:
  image: mongo:4.0
  container_name: rydell-mongo-config-03
  command: mongod --port 27017 --configsvr --replSet rs-config-server
  volumes:
    - ./scripts:/scripts
  ports:
    - 27121:27017
  links:
    - configsvr02
