version: "3"

services:
  
  # Mongo Router server
  mongos:
    hostname: mongos
    image: mongo:latest
    ports:
      - 27017:27017
    command: mongos --port 27017 --configdb configserver/cfgsvr1:27017,cfgsvr2:27017 --bind_ip_all
    volumes:
      - ./scripts:/scripts
    depends_on: 
      - cfgsvr1
      - cfgsvr2
      - shrdsvr1_1
      - shrdsvr1_2
      - shrdsvr1_3

  # Mongodb Config Server
  cfgsvr1:
    container_name: cfgsvr1
    image: mongo:latest
    expose:
      - 27017
    command: mongod --port 27017 --configsvr --replSet configserver
    environment: 
      - MONGODB_REPLICA_SET_MODE=primary

  cfgsvr2:
    container_name: cfgsvr2
    image: mongo:latest
    expose:
      - 27017
    command: mongod --port 27017 --configsvr --replSet configserver
    environment: 
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=cfgsvr1
    links:
      - cfgsvr1
  
  # Mongodb Shard Server
  shrdsvr1_1:
    image: mongo:latest
    ports:
      - 27017
    volumes:
      - /shrdsvr1_data1:/data/db
    command: mongod --shardsvr --port 27017 --replSet shrd1
  
  shrdsvr1_2:
    image: mongo:latest
    ports:
      - 27018
    volumes:
      - /shrdsvr1_data2:/data/db
    command: mongod --shardsvr --port 27018 --replSet shrd1
  
  shrdsvr1_3:
    image: mongo:latest
    ports:
      - 27019
    volumes:
      - /shrdsvr1_data3:/data/db
    command: mongod --shardsvr --port 27019 --replSet shrd1


volumes:
  shrdsvr1_data1:
  shrdsvr1_data2:
  shrdsvr1_data3:
    